{{- if gt (int .Values.compactor.replicas) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "loki.compactorFullname" . }}
  labels:
    {{- include "loki.compactorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "loki.compactorSelectorLabels" . | nindent 6 }}
  maxUnavailable: 1
{{- end }}
