apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.compactorFullname" . }}-headless
  labels:
    {{- include "loki.compactorSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.compactorSelectorLabels" . | nindent 4 }}
